language: node_js
node_js:
  - 13.7.0
cache:
  directories:
    - node_modules
install:
  - npm install marked bootstrap
script:
  - npm test
deploy:
  provider: script
  script: now --token=$NOW_TOKEN --confirm --no-clipboard 
  skip_cleanup: true
  on:
    branch: master
